name: mysql blog
description: Blog of Shevckcccc
url: "http://mysql.im"
baseurl: /

# Author info
author_name: Shevckcccc
author_image_path: /images/author-image.jpeg
author_bio: |
    iOS程序员<br>
    创业者<br>

# External services
github_url: "https://github.com/Shevckcccc"
email: "yuyk1113@gmail.com"

# Markdown rendering
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false
highlighter: pygments
